env:
  TERM: xterm-256color

padding:
  x: 2
  y: 2

window:
  decorations: none
  dynamic_padding: true
  # startup_mode: Maximized

debug:
  render_timer: false

bell:
  animation: EaseOutExpo
  duration: 0

background_opacity: 1.0

key_bindings:
 - { key: V,        mods: Command, action: Paste                        }
 - { key: C,        mods: Command, action: Copy                         }
 - { key: Key0,     mods: Command, action: ResetFontSize                }
 - { key: Equals,   mods: Command, action: IncreaseFontSize             }
 - { key: Minus,    mods: Command, action: DecreaseFontSize             }
 - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
 - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
 - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
 - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
 - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
 - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
 - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
 - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
 - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
 - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
 - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
 - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
 - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
 - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
 - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
 - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
 - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
 - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
 - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
 - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
 - { key: B,        mods: Alt,     chars: "\x1bb"                       }
 - { key: F,        mods: Alt,     chars: "\x1bf"                       }
 - { key: D,  mods: Alt,           chars: "\x1bd"                       }

colors:
  primary:
    background: '0x292C3E'
    foreground: '0xEBEBEB'

  cursor:
   text: '0xFF261E'
   cursor: '0xFF261E'

  normal:
    black:   '0x0d0d0d'
    red:     '0xFF301B'
    green:   '0xA0E521'
    yellow:  '0xFFC620'
    blue:    '0x1BA6FA'
    magenta: '0x8763B8'
    cyan:    '0x21DEEF'
    white:   '0xEBEBEB'

  bright:
    black:   '0x6D7070'
    red:     '0xFF4352'
    green:   '0xB8E466'
    yellow:  '0xFFD750'
    blue:    '0x1BA6FA'
    magenta: '0xA578EA'
    cyan:    '0x73FBF1'
    white:   '0xFEFEF8'

font:
  size: 14
  normal:
    family: Fira Code
    style: Regular

  bold:
    family: Fira Code
    style: Bold

  italic:
    family: Fira Code
    style: Italic

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

  use_thin_strokes: false
