#!/usr/bin/env bash

set -euo pipefail

rsync -v --archive "$HOME/Library/Application Support/Steam/steamapps/common/Rocksmith2014/dlc/" rsync://tobias@nas.local/storage_tobias/tobias/Rocksmith_DLCs
rsync -v --archive "$HOME/Documents/Arduino/" rsync://tobias@nas.local/storage_tobias/tobias/Documents/Arduino
rsync -v --archive "$HOME/Documents/Books/" rsync://tobias@nas.local/storage_tobias/tobias/Documents/Books
rsync -v --archive "$HOME/Documents/Guitar/" rsync://tobias@nas.local/storage_tobias/tobias/Documents/Guitar
rsync -v --archive "$HOME/Documents/OpenSCAD/" rsync://tobias@nas.local/storage_tobias/tobias/Documents/OpenSCAD
rsync -v --archive "$HOME/Pictures/" rsync://tobias@nas.local/storage_tobias/tobias/Pictures
