name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ignite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Ignite
      run: ./ignite.sh $(pwd)
